/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Components: typeof import('./../src/components/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    Head: typeof import('./../src/components/head/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IEpFilter: typeof import('~icons/ep/filter')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    Language: typeof import('./../src/components/demo/Language.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    Routertest: typeof import('./../src/components/routertest/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
